export const CAPTCHA_SITE_KEY_V3 = '6LeBw48UAAAAAKdEZJS0WvRM3YId-s1kaw6rd1O8';
export const CAPTCHA_VERSION_3 = 'V3';
export const CAPTCHA_SITE_KEY_V2 = '6LdGrVUUAAAAAJ2sLr5qoMu7XMPDIxZ1MX-HRT72';
export const CAPTCHA_VERSION_2 = 'V2';
